//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakultet_IS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prijavas
    {
        public string BI { get; set; }
        public double IspitID { get; set; }
        public Nullable<double> Ocena { get; set; }
    
        public virtual Ispits Ispits { get; set; }
        public virtual Students Students { get; set; }
    }
}
